/* SOC dashboard client: reads and updates the local SOC Lab API. */
let dashboardState = null;
let selectedAlert = null;
const feed = document.querySelector('#alertFeed');
const escapeHtml = value => String(value).replace(/[&<>'"]/g, c => ({'&':'&lt;','>':'&gt;','&amp;':'&amp;',"'":'&#39;','"':'&quot;'}[c]));
const relativeTime = iso => { const s=Math.max(0,Math.floor((Date.now()-new Date(iso))/1000)); return s<60?'now':`${Math.floor(s/60)}m`; };
function renderAlerts(alerts) { feed.innerHTML=alerts.slice(0,6).map(a=>`<article class="alert" data-id="${a.id}"><span class="severity-badge sev-${a.severity}">${a.severity.toUpperCase()}</span><span class="alert-name"><b>${escapeHtml(a.name)}</b><small>${a.technique} · ${a.status}</small></span><span class="entity">${escapeHtml(a.entity)}</span><time>${relativeTime(a.timestamp)}</time></article>`).join(''); }
function updateDashboard(data) {
  dashboardState=data; renderAlerts(data.alerts);
  document.querySelector('#risk').textContent=data.agent.risk;
  document.querySelector('#agentThought').textContent=data.agent.thought;
  document.querySelector('.progress-label b').textContent=`${data.agent.containment}%`;
  document.querySelector('.progress i').style.width=`${data.agent.containment}%`;
  document.querySelector('.agent-actions').innerHTML=data.agent.actions.map(a=>`<span>✓ ${escapeHtml(a)}</span>`).join('') + (data.agent.approvalPending?'<span>◌ Awaiting analyst approval</span>':'<span>✓ Analyst approval complete</span>');
  document.querySelector('#attackers').innerHTML=data.attackers.map(x=>`<div class="attacker"><span>${escapeHtml(x.ip)}<small> · ${escapeHtml(x.source)}</small></span><i><b style="width:${x.score}%"></b></i><strong>${x.score}</strong></div>`).join('');
  if (traffic) { traffic.data.datasets[0].data=data.traffic; traffic.data.datasets[1].data=data.traffic.map(x=>Math.max(4,Math.round(x*.28))); traffic.update('none'); }
}
async function loadDashboard() { try { const response=await fetch('/api/dashboard'); if(!response.ok) throw new Error('API unavailable'); updateDashboard(await response.json()); } catch(error) { document.querySelector('#agentThought').textContent='API offline — start the SOC Lab server to enable live telemetry.'; console.error(error); } }
feed.onclick=e=>{ const row=e.target.closest('.alert'); if(!row||!dashboardState)return; selectedAlert=dashboardState.alerts.find(a=>a.id===row.dataset.id); if(!selectedAlert)return; document.querySelector('#drawerTitle').textContent=selectedAlert.name; document.querySelector('.drawer-risk b').textContent=`${selectedAlert.risk} / 100`; document.querySelector('.drawer dl').innerHTML=`<dt>MITRE MAPPING</dt><dd>${selectedAlert.technique}</dd><dt>DETECTION RULE</dt><dd>${selectedAlert.rule}</dd><dt>AI ANALYSIS</dt><dd>${escapeHtml(selectedAlert.analysis)}</dd>`; document.querySelector('.drawer pre').textContent=selectedAlert.payload; document.querySelector('#drawer').classList.add('open'); };
document.querySelector('#closeDrawer').onclick=()=>document.querySelector('#drawer').classList.remove('open');
document.querySelector('.contain').onclick=async()=>{ if(!selectedAlert)return; const button=document.querySelector('.contain'); button.disabled=true; button.textContent='Executing containment…'; try { await fetch('/api/containment',{method:'POST'}); await fetch(`/api/alerts/${selectedAlert.id}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'Contained'})}); await loadDashboard(); button.textContent='Containment completed ✓'; } catch { button.textContent='Containment failed — retry'; } finally { button.disabled=false; } };
function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})} clock(); setInterval(clock,1000);
Chart.defaults.color='#7f9ba3'; Chart.defaults.font.family='DM Mono'; const grid={color:'#1a3540'};
const traffic=new Chart(document.querySelector('#trafficChart'),{type:'line',data:{labels:['09:00','09:10','09:20','09:30','09:40','09:50','10:00'],datasets:[{label:'Packets',data:[42,57,45,74,61,93,76],borderColor:'#59e7ef',backgroundColor:'#59e7ef18',fill:true,tension:.4,pointRadius:0,borderWidth:2},{label:'Anomalies',data:[9,12,8,22,12,32,19],borderColor:'#ff6977',tension:.4,pointRadius:0,borderWidth:1.5}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{grid,ticks:{font:{size:9}}},y:{grid,ticks:{font:{size:9}}}}}});
new Chart(document.querySelector('#severityChart'),{type:'doughnut',data:{labels:['Critical','High','Medium','Low'],datasets:[{data:[18,34,31,17],backgroundColor:['#ff6977','#ffbd69','#59e7ef','#5985a5'],borderWidth:0,cutout:'72%'}]},options:{plugins:{legend:{display:false}},responsive:true}});
loadDashboard(); let refreshTimer=setInterval(loadDashboard,7000);

/* Console navigation and controls. Kept client-side so every dashboard view remains live. */
document.querySelector('h1').textContent='Good morning, snickerdoodle.';
const panelFor = {Overview:'header', 'Live Alerts':'.alerts-panel', 'Threat Intel':'.attackers', Forensics:'#drawer', Playbooks:'.agent', MITRE:'.severity'};
const navLinks=[...document.querySelectorAll('aside nav a')];
navLinks.forEach(link=>link.addEventListener('click',()=>{
  const label=link.querySelector('span')?.textContent.trim() || '';
  navLinks.forEach(item=>item.classList.remove('active')); link.classList.add('active');
  if(label==='Forensics'){ if(!selectedAlert && dashboardState) { selectedAlert=dashboardState.alerts[0]; feed.querySelector('.alert')?.click(); } else document.querySelector('#drawer').classList.add('open'); return; }
  document.querySelector(panelFor[label])?.scrollIntoView({behavior:'smooth',block:'start'});
}));
const controls=document.createElement('div'); controls.innerHTML=`<div class="dash-overlay" id="dashSearch"><section><button class="dash-close">×</button><p class="eyebrow">SEARCH ALERTS</p><input id="alertSearch" placeholder="Search alert, entity, or MITRE ID" autocomplete="off"><div class="dash-results"></div></section></div><div class="dash-overlay" id="dashNotifications"><section><button class="dash-close">×</button><p class="eyebrow">RECENT NOTIFICATIONS</p><div class="dash-results"></div></section></div><div class="dash-overlay" id="dashSettings"><section><button class="dash-close">×</button><p class="eyebrow">CONSOLE SETTINGS</p><label class="dash-setting"><span>Auto-refresh telemetry</span><input id="autoRefresh" type="checkbox" checked></label><label class="dash-setting"><span>Compact alert view</span><input id="compactAlerts" type="checkbox"></label></section></div><div id="dashToast"></div>`; document.body.append(controls);
const controlStyle=document.createElement('style'); controlStyle.textContent=`.dash-overlay{display:none;position:fixed;inset:0;background:#02090baa;z-index:8;place-items:center;padding:20px}.dash-overlay.open{display:grid}.dash-overlay section{position:relative;width:min(530px,100%);background:#0b1b22;border:1px solid #4c929b;padding:28px;box-shadow:0 16px 60px #000}.dash-close{position:absolute;right:12px;top:8px;border:0;background:none;color:#8fced3;font-size:25px;cursor:pointer}.dash-overlay input{width:100%;margin:10px 0;border:1px solid #31545e;background:#071217;padding:13px;color:#ecf8f8;font:12px 'DM Mono';outline:none}.dash-results{max-height:260px;overflow:auto}.search-item{padding:12px 2px;border-bottom:1px solid #1b3740;cursor:pointer;font-size:12px}.search-item small{display:block;margin-top:4px}.dash-setting{display:flex;justify-content:space-between;padding:16px 0;border-top:1px solid #1e3b44;font-size:12px;color:#c4d9dc}.dash-setting input{width:auto;margin:0;accent-color:#59e7ef}#dashToast{position:fixed;right:28px;bottom:28px;z-index:12;background:#d8f6f7;color:#08191e;padding:12px 16px;font:11px 'DM Mono';transform:translateY(90px);opacity:0;transition:.25s}#dashToast.show{transform:none;opacity:1}.header-tools .live{width:auto;color:#6ef19e;cursor:pointer}`; document.head.append(controlStyle);
const compactStyle=document.createElement('style');compactStyle.textContent='#alertFeed.compact-alerts .alert{padding-top:7px;padding-bottom:7px}#alertFeed.compact-alerts .alert-name small{display:none}';document.head.append(compactStyle);const openOverlay=id=>document.querySelector(id).classList.add('open'); const closeOverlays=()=>document.querySelectorAll('.dash-overlay').forEach(x=>x.classList.remove('open'));
document.querySelectorAll('.dash-close').forEach(b=>b.onclick=closeOverlays); document.querySelectorAll('.dash-overlay').forEach(x=>x.onclick=e=>{if(e.target===x)closeOverlays()});
const headerButtons=document.querySelectorAll('.header-tools button'); document.querySelector('.header-tools .live').onclick=async()=>{await loadDashboard(); showToast('Telemetry refreshed successfully.');}; headerButtons[0].onclick=()=>{openOverlay('#dashSearch');document.querySelector('#alertSearch').focus();};
document.querySelector('.side-bottom>a').onclick=()=>openOverlay('#dashSettings');
document.querySelector('#alertSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim(), box=document.querySelector('#dashSearch .dash-results'); const matches=(dashboardState?.alerts||[]).filter(a=>`${a.name} ${a.entity} ${a.technique}`.toLowerCase().includes(q)); box.innerHTML=q?(matches.length?matches.map(a=>`<div class="search-item" data-id="${a.id}"><b>${escapeHtml(a.name)}</b><small>${escapeHtml(a.entity)} · ${a.technique}</small></div>`).join(''):'<div class="search-item">No matching alerts.</div>'):'';};
document.querySelector('#dashSearch .dash-results').onclick=e=>{const item=e.target.closest('[data-id]');if(!item)return;closeOverlays();feed.querySelector(`[data-id="${item.dataset.id}"]`)?.click();};
const notificationButton=headerButtons[1];
notificationButton.onclick=()=>{const box=document.querySelector('#dashNotifications .dash-results');box.innerHTML=(dashboardState?.alerts||[]).slice(0,4).map(a=>`<div class="search-item"><b>${escapeHtml(a.name)}</b><small>${a.severity.toUpperCase()} · ${relativeTime(a.timestamp)} · ${escapeHtml(a.entity)}</small></div>`).join('');openOverlay('#dashNotifications');};
document.querySelector('#autoRefresh').onchange=e=>{clearInterval(refreshTimer);if(e.target.checked)refreshTimer=setInterval(loadDashboard,7000);showToast(e.target.checked?'Auto-refresh enabled.':'Auto-refresh paused.');};document.querySelector('#compactAlerts').onchange=e=>{feed.classList.toggle('compact-alerts',e.target.checked);showToast(e.target.checked?'Compact alert view enabled.':'Standard alert view enabled.');};
function showToast(message){const toast=document.querySelector('#dashToast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}
