/* SOC Lab landing-page interactions and generated content */
const attacks=[['Nmap Reconnaissance','T1046','Network service discovery through targeted port scanning.','Medium'],['SYN Flood DoS','T1499','High-volume SYN packets exhaust connection capacity.','Critical'],['Hydra FTP Brute Force','T1110','Repeated credential attempts against FTP service.','High'],['Hydra SSH Brute Force','T1110','Password spray against remote administration.','High'],['Directory Enumeration','T1083','Forced browsing reveals exposed application paths.','Medium'],['SQL Injection Simulation','T1190','Malicious query input targets public-facing app.','Critical'],['Web XSS Simulation','T1059','Injected script payload attempts client-side execution.','Medium']];
const defense=[['◫','Windows Defender Firewall','Enforces host-based network policy.',32,'18.4k events'],['◉','Snort IDS','Detects malicious network patterns.',68,'42.1k packets'],['⌁','Wireshark','Captures and inspects packet evidence.',44,'8.7k flows'],['▣','Sysmon','Enriches endpoint process telemetry.',76,'12.9k events'],['>_','PowerShell Logging','Records scripting and command activity.',55,'6.2k commands'],['▤','Windows Event Logs','Centralizes security audit records.',83,'31.6k events'],['✦','AI SOC Agent','Correlates and triages security signals.',64,'864 assessments']];
const techniques={T1046:['Network Service Discovery','Adversaries scan a network to discover available services and listening ports.','Snort detects a horizontal TCP SYN scan above 25 unique ports in 60 seconds.','Segment networks and alert on abnormal scan volume.','[HIGH] NMAP_SCAN src=10.10.10.24 dst=10.10.10.0/24'],T1110:['Brute Force','Adversaries attempt to gain access by guessing account passwords.','Correlate five or more failed authentications from a single source.','Use MFA, rate limits, and account lockout controls.','[HIGH] BRUTE_FORCE service=SSH failures=17 src=10.10.10.24'],T1499:['Endpoint Denial of Service','Adversaries may degrade or block availability.','Flag SYN/ACK ratio anomaly and per-source connection spike.','Apply rate limiting and block malicious source ranges.','[CRITICAL] SYN_FLOOD pps=14820 target=172.16.10.8'],T1190:['Exploit Public-Facing Application','An exposed application is targeted to gain initial access.','WAF signature matches SQL metacharacters in query parameters.','Patch applications and validate input server-side.','[CRITICAL] SQLI pattern=union-select uri=/login'],T1078:['Valid Accounts','Compromised credentials are used to access a system.','Detect anomalous sign-in geography and unusual authentication sequence.','Use phishing-resistant MFA and monitor privileged sessions.','[MEDIUM] VALID_ACCOUNT user=svc_backup source=external'],T1059:['Command and Scripting Interpreter','Adversaries may execute commands through an interpreter.','Sysmon detects encoded PowerShell with suspicious parent process.','Constrain PowerShell and allow-list scripts.','[HIGH] POWERSHELL_ENCODED host=WIN-DC01'],T1021:['Remote Services','Adversaries may use remote services to move laterally.','Correlate RDP failure bursts with new remote service sessions.','Restrict remote access and enforce segmentation.','[HIGH] RDP_BRUTE_FORCE destination=WIN-SRV02'],T1071:['Application Layer Protocol','Command and control traffic uses common application protocols.','Identify periodic DNS requests with high-entropy subdomains.','Filter DNS and inspect egress traffic.','[MEDIUM] DNS_TUNNEL entropy=4.82 host=client-17']};
document.querySelector('#attackGrid').innerHTML=attacks.map((a,i)=>`<article class="attack-card reveal"><span class="tag">SIM-${String(i+1).padStart(2,'0')} · ${a[1]}</span><h3>${a[0]}</h3><p>${a[2]}</p><footer><span>RISK: ${a[3]}</span><span class="status">● DETECTED</span></footer></article>`).join('');
document.querySelector('#defenseGrid').innerHTML=defense.map(d=>`<article class="defense-card reveal"><span class="arch-icon">${d[0]}</span><h3>${d[1]}</h3><p>${d[2]}</p><div class="meter"><i style="width:${d[3]}%"></i></div><div class="defense-meta"><span>● ONLINE</span><span>${d[4]}</span></div></article>`).join('');
document.querySelector('#toolsGrid').innerHTML=['Kali Linux','Snort IDS','Wireshark','Windows Firewall','PowerShell','Sysmon','Nmap','Hydra','MITRE ATT&CK','HTML5','CSS3','JavaScript'].map((x,i)=>`<article class="tool"><i>${['◒','◉','⌁','◫','>_','▣'][i%6]}</i><b>${x}</b></article>`).join('');
document.querySelector('#mitreGrid').innerHTML=Object.keys(techniques).map((id,i)=>`<button class="tech ${i===2||i===3?'critical':i<6?'hot':''}" data-id="${id}">${id}</button>`).join('');
const modal=document.querySelector('#techModal');document.querySelectorAll('.tech').forEach(el=>el.onclick=()=>{let d=techniques[el.dataset.id];document.querySelector('#modalTitle').textContent=`${el.dataset.id} · ${d[0]}`;document.querySelector('#modalDesc').textContent=d[1];document.querySelector('#modalLogic').textContent=d[2];document.querySelector('#modalMitigation').textContent=d[3];document.querySelector('#modalAlert').textContent=d[4];modal.classList.add('show')});document.querySelector('.close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const metricObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;document.querySelectorAll('[data-count]').forEach(n=>{let target=+n.dataset.count,suffix=n.dataset.suffix||'',start=performance.now();let tick=now=>{let p=Math.min(1,(now-start)/1100);n.textContent=(target*(1-Math.pow(1-p,3))).toFixed(target%1?1:0)+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});metricObserver.disconnect()}),{threshold:.4});metricObserver.observe(document.querySelector('#metrics'));
document.addEventListener('mousemove',e=>{document.querySelector('.cursor-glow').style.left=e.clientX+'px';document.querySelector('.cursor-glow').style.top=e.clientY+'px'});
